Repository revaturelabs/biforce, pull requests merged in 2019-01, with the labels that each got.

#15 Vencente Gilmore
  names/vencente-gilmore
Labels: wontfix

#49 Terrance-Mount touch added
  names/terrance-mount
Labels: low

#51 add all name
  names/all
Labels: low

#64 Revert "Spark example is working "
  oozie/README.md
  oozie/SparkExample/SparkWordCount/.gitignore
  oozie/SparkExample/SparkWordCount/output/test/._SUCCESS.crc
  oozie/SparkExample/SparkWordCount/output/test/.part-00000.crc
  oozie/SparkExample/SparkWordCount/output/test/.part-00001.crc
  oozie/SparkExample/SparkWordCount/output/test/_SUCCESS
  oozie/SparkExample/SparkWordCount/output/test/part-00000
  oozie/SparkExample/SparkWordCount/output/test/part-00001
  oozie/SparkExample/SparkWordCount/output/theOutput
  oozie/SparkExample/SparkWordCount/pom.xml
  oozie/SparkExample/SparkWordCount/src/main/java/com/revature/Driver.java
  oozie/SparkExample/SparkWordCount/src/main/java/com/revature/DriverYARN.java
  oozie/SparkExample/SparkWordCount/src/main/java/com/revature/spark/WordCount.java
  oozie/SparkExample/job.properties
  oozie/SparkExample/workflow.xml
Labels: high

#59 Rename folder for issue and PR templates
  docs/CODEOWNERS
  docs/ISSUE_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: cosmetic, low

#66 Physical cluster directions - william steele
  physical-cluster/Physical_Cluster_Directions
Labels: low

#109 [spark] Add README for Biforce ML
  biforce/spark/battery_analyzer/README.md
Labels: cosmetic, medium
